---
ID: "2c003ea6-351f-4a0a-b9e0-0f57b6d7e24e"
Parent: "c6d28310-014c-4f69-b1eb-2a596d600921"
Template: "c6d28310-014c-4f69-b1eb-2a596d600921"
Path: /sitecore/templates/Feature/SitecoreShades/Hero/Rendering Parameters/StandBlog Carousel/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
